name: Release Builds
on: push
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

jobs:
  build-and-store-artifact:
    name: Build 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ macos-latest ]
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Make GNU
      if: matrix.os != 'windows-latest'
      working-directory: ./buckshot
      run: qmake ; make ; ls -al
      shell: bash
    - name: Make Windows
      if: matrix.os == 'windows-latest'
      working-directory: ./buckshot
      run: |
        dir
        qmake
        dir
        #mingw32-make 
        #dir
        nmake
        dir
        dir release

    - name: Package OSX Test
      if: matrix.os == 'macos-latest'
      run: |
        echo "----1"
        ls -al
        echo "----2"
        ls -al
        echo "----3"
        macdeployqt buckshot.app
        ls -al buckshot.app

      
